name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.1.0
        with:
          version: '0.56.0'
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Print buf version
        if: success()
        run: |
          buf --version
      - name: Install dependencies
        run: |
          make setup
      - name: Generate code
        run: |
          make proto-gen
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ github.event.head_commit.message }} (auto-generate pb files)
